### PR TITLE
More work on streams images

### PR DESCRIPTION
**Pull request by jroper**
* Changed image directory configuration so that images should now render in GitHub.
* Switched to using SVG instead of PNG because asciidoctor had a problem including interlaced PNGs in the PDF output.
* Added some more images, and reworked the docs a little bit to be more explicit about stages vs graphs and how they compose.
* Changed the shapes of stream stages to be pentagons, convex pentagons chevrons rather than rectangles to make their shapes a little clearer.

### CODE REVIEW

**Comment by jroper** [comment]
To view the finished product, view here (now GitHub can find the images so it renders nicely):

https://github.com/jroper/microprofile-reactive/blob/417c0b99478f4e5173f405d825ef7764e628f63d/streams/spec/src/main/asciidoc/architecture.asciidoc

**Comment by cescoffier** [comment]
I was thinking about changing the colors to reuse the MP colors. I know... purely cosmetic.

**Comment by jroper** [comment]
Ok, so what are MP colors? For yellow, the [MP logo](https://microprofile.io/app/images/logo.png) uses `#FDB71C`, while the [website stylesheets](https://github.com/microprofile/microprofile-site/blob/f641a08b40cd9fd9a71818f140935d2da7caf9c4/src/main/static/assets/styles/_variables.sass) use `#EFC94C`. The latter is used as a background colour, so we should probably use the former for lines in diagrams. The other MP colour is blue, but the website itself never uses this colour apart from in its [favicon](https://microprofile.io/app/images/favicon.png), where it uses `#1F3A50`. The [original logo announcement blog post](https://microprofile.io/blog/2017/08/eclipse-microProfile-has-a-brand-new-logo) has a logo sporting `#19405B` as its blue. They're not terribly different, the latter is a bit more blue. So I'm going for the latter. So the two colours are `#FDB71C` and `#19405B`.

I've updated this PR with the images using those colours.

**Comment by jroper** [comment]
And the updated link for previewing the images in the documentation is:

https://github.com/jroper/microprofile-reactive/blob/19f72176178d0eeafb5f896326381d8d1059da1e/streams/spec/src/main/asciidoc/architecture.asciidoc

**Comment by jroper** [comment]
I've updated the colours again according to the discussion on the [mailing list](https://groups.google.com/d/msg/microprofile/kfddxgFg9IU/LY93SQqACQAJ), a very slight (almost unnoticeable) change to the blue from `#19405B` to `#123E5C`. Here's the link to preview:

https://github.com/jroper/microprofile-reactive/blob/d52d277751ae0994eabf46151e1a0df81db073a9/streams/spec/src/main/asciidoc/architecture.asciidoc

**Comment by jroper** [comment]
Merging as it was decided in the Reactive Hangout to merge this.

**Pull request merged**
